# Generated by Django 3.0.7 on 2020-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('birth_date', models.DateTimeField()),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('employee_id', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('department', models.CharField(max_length=50)),
                ('work_location', models.CharField(max_length=50)),
                ('supervisor', models.CharField(max_length=50)),
                ('emergency_contact_name', models.CharField(max_length=50)),
                ('emergency_contact_number', models.CharField(max_length=50)),
                ('salary', models.FloatField(blank=True, default='$0.00')),
                ('phone_number', models.CharField(blank=True, max_length=250)),
                ('email_address', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
