# Generated by Django 3.0.7 on 2020-07-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
